parameters:
    jonasarts.opentbs.class: jonasarts\Bundle\OpenTBSBundle\OpenTBS\OpenTBS

services:
    opentbs:
        class: "%jonasarts.opentbs.class%"
        arguments: []
        public: true

    jonasarts\Bundle\OpenTBSBundle\OpenTBS\OpenTBS: ~